version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seiron-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_ORCHESTRATOR_API=${VITE_ORCHESTRATOR_API:-http://localhost:3001/api}
      - VITE_ORCHESTRATOR_WS=${VITE_ORCHESTRATOR_WS:-ws://localhost:3001}
      - NEXT_PUBLIC_ELEVENLABS_API_KEY=${NEXT_PUBLIC_ELEVENLABS_API_KEY:-}
      - NEXT_PUBLIC_ELEVENLABS_VOICE_ID=${NEXT_PUBLIC_ELEVENLABS_VOICE_ID:-}
    # volumes:
    #   # For development hot reload (optional)
    #   - ./frontend:/app
    #   - /app/node_modules
    networks:
      - seiron-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  seiron-network:
    driver: bridge