version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: seiron-backend
    ports:
      - "8000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Supabase is used instead of local postgres
      - DATABASE_URL=${SUPABASE_DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${FRONTEND_URL}
      # Supabase
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # Add your API keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID}
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - seiron-net

  redis:
    image: redis:7-alpine
    container_name: seiron-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - seiron-net

  nginx:
    image: nginx:alpine
    container_name: seiron-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - seiron-net

volumes:
  postgres_data:
  redis_data:

networks:
  seiron-net:
    driver: bridge