services:
  # Redis for testing
  redis:
    image: redis:7-alpine
    container_name: seiron-redis-test
    ports:
      - "6380:6379"
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Backend Test Runner
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: test
    container_name: seiron-backend-test
    environment:
      - NODE_ENV=test
      - REDIS_URL=redis://redis:6379
      - SEI_RPC_URL=https://evm-rpc-testnet.sei-apis.com
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/coverage:/app/coverage
    depends_on:
      redis:
        condition: service_healthy
    command: ["npm", "test"]

  # Frontend Test Runner
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: seiron-frontend-test
    environment:
      - NODE_ENV=test
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/coverage:/app/coverage
    command: ["npm", "test"]

volumes:
  test-data:

networks:
  default:
    name: seiron-network-test