services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seiron-frontend-test
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://seiron-git-dev-angleitos-projects.vercel.app
      - VITE_WS_URL=wss://seiron-git-dev-angleitos-projects.vercel.app
      - VITE_PRIVY_APP_ID=cmcpivwht00pnl40lq59l9j9e
      - VITE_SEI_RPC_URL=https://evm-rpc.sei-apis.com
      - VITE_ORCHESTRATOR_API=https://seiron-git-dev-angleitos-projects.vercel.app
      - VITE_ORCHESTRATOR_WS=wss://seiron-git-dev-angleitos-projects.vercel.app
      - ORCHESTRATOR_ENDPOINT=https://seiron-git-dev-angleitos-projects.vercel.app
      - ORCHESTRATOR_WS_ENDPOINT=wss://seiron-git-dev-angleitos-projects.vercel.app
      - VITE_ELEVENLABS_API_KEY=sk_db0534f892d448c53e5124c259f2179a0b5dd71fd920df0d
      - VITE_ELEVENLABS_VOICE_ID=oU7wACaoBq6CiGbPjU1k
      - VITE_VOICE_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  default:
    name: seiron-test-network
