[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
test = "contracts/test"
script = "contracts/script"
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"

# Compiler settings
solc_version = "0.8.21"
optimizer = true
optimizer_runs = 200
via_ir = false

# EVM settings
evm_version = "london"

# Gas settings
gas_limit = 30000000
gas_price = 1000000000

# Formatter settings
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

# Fuzz settings
fuzz = { runs = 1000, max_test_rejects = 65536, seed = 0x3e8 }
invariant = { runs = 256, depth = 15, fail_on_revert = false, call_override = false, dictionary_weight = 40, include_storage = true, include_push_bytes = true }

# Sei Network Configuration
[rpc_endpoints]
sei_testnet = "https://evm-rpc-testnet.sei-apis.com"
sei_mainnet = "https://evm-rpc.sei-apis.com"

[etherscan]
sei_testnet = { key = "${SEI_TESTNET_API_KEY}", url = "https://seitrace.com/api" }
sei_mainnet = { key = "${SEI_MAINNET_API_KEY}", url = "https://seitrace.com/api" }

# Profile for testing
[profile.test]
src = "contracts/src"
test = "contracts/test"
gas_limit = 50000000
fuzz = { runs = 10000 }

# Profile for production deployment
[profile.production]
optimizer = true
optimizer_runs = 1000000
via_ir = true
gas_limit = 30000000

# Profile for CI
[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 20 }