#!/bin/bash

echo "🔍 Getting VPS Information"
echo "=========================="
echo ""
echo "Option 1: If you know your VPS IP address"
echo "  Use: ./deploy-to-vps.sh YOUR.IP.ADDRESS"
echo ""
echo "Option 2: Find your VPS IP by logging in:"
echo "  ssh root@your-vps"
echo "  Then run: curl ifconfig.me"
echo ""
echo "Option 3: Check your VPS provider's dashboard:"
echo "  - DigitalOcean: Droplets page"
echo "  - AWS: EC2 Instances page"
echo "  - Linode: Linodes page"
echo "  - Vultr: Instances page"
echo ""
echo "Once you have your IP, update Vercel with:"
echo "  VITE_API_URL=http://YOUR.IP.ADDRESS:8000"
echo "  VITE_WS_URL=ws://YOUR.IP.ADDRESS:8000"